services:
  db:
    image: mongo
    container_name: sleepr-db
    restart: always
    ports:
      - 27021:27017
    env_file:
      - ./.env.local

  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: Development
    container_name: sleepr-reservations
    command: pnpm start:dev reservations
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: Development
    container_name: sleepr-auth
    command: pnpm start:dev auth
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
